### PR TITLE
Add support for IDE Build 223.*

### PR DESCRIPTION
**Pull request by cchulo**
- Adds support for IDE Build 223.*
- Incremented minor version to 1.0.6

Screenshot_20221205_013936

### CODE REVIEW

**Comment by walt-grace** [comment]
I need to take care anyway for a release. I will do everything at once because I wouldn't like to just bump up and release and to see that there were no breaking changes.

**Comment by cchulo** [comment]
@walt-grace sounds good, feel free to close this if you don't see any purpose

btw, I noticed a couple of things wanted to know:
- unit tests don't seem to pass, not even with latest master, is this a known issue?
- what is the purpose of 1.0.1? It looks like it support 223.*, obviously its missing things from 1.0.2 - 1.0.5, but am wondering if 1.0.1 was versioned to support 223 on purpose or it was a mistake?

**Comment by walt-grace** [comment]
Hi @cchulo 
* Yep, that's precisely the reason why I was not in favour of just bumping up and release - unit test must for sure pass. I'll have a look why they didn't pass. 
* It definitely could be that I messed up with versions. I think it's where I still tried to understand how this all works so assumebly I did stupid things. I cannot remember what I did there exactly.

**Comment by walt-grace** [comment]
@cchulo 
Sorry for the super late response. Update was submitted. I assume they will approve in on Monday. 
Have a nice weekend

**Comment by cchulo** [comment]
sounds good! thanks for your hard work!

**Pull request closed without merging**
