### PR TITLE
Add support for 2024.2

### PR DESCRIPTION
**Pull request by EugeneDraitsev**
Hi!

Thank you for the great plugin!
It would be great if you can add support for 2024.2 since this version is already in beta and will be in RC  soon

### CODE REVIEW

**Comment by walt-grace** [comment]
Hi @EugeneDraitsev 
I'm already working on version 1.1.2 which will be released in the next the next days. I can certainly added that as well but that will take few days.
In the meantime, just build the plugin locally with the IDE version update and you can install it manually until I will release. 
If you don't know how:
1. Run the gradle task buildPlugin locally after you changes. This will produce a jar into the 'distributions' dir in the 'build' directory. 
2. Open settings -> plugin -> settings wheel top right corner -> install plugin from disk -> choose the jar.

**Comment by EugeneDraitsev** [comment]
Thank you for the detailed response!
I'll wait until official release, feel free to close this PR if you don't really need it

**Comment by walt-grace** [comment]
@EugeneDraitsev All good now?

**Comment by EugeneDraitsev** [comment]
@walt-grace yeah, works fine with the latest version! Thanks a lot!

**Pull request closed without merging**
